version: 1.0.{build}
image: Visual Studio 2019
platform: x64

environment:
  COMPILER: msvc2019
  matrix:
    # Interleave PYTHON, ARCH and GEOS_VERSION
#    - PYTHON: "C:\\Python35-x64"
#      ARCH: x64
#      GEOS_VERSION: "3.5.2"
    - PYTHON: "C:\\Python36"
      ARCH: x86
      GEOS_VERSION: "3.6.4"
#    - PYTHON: "C:\\Python37-x64"
#      ARCH: x64
#      GEOS_VERSION: "3.7.3"
#    - PYTHON: "C:\\Python38"
#      ARCH: x86
#      GEOS_VERSION: "3.8.1"
#    - PYTHON: "C:\\Python39-x64"
#      ARCH: x64
#      GEOS_VERSION: "3.8.1"

init:
- cmd: SET PATH=c:\python36;c:\python36\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files (x86)\7-Zip\;C:\Program Files\Git\usr\bin;C:\Users\appveyor\AppData\Roaming\Python\Python36\Scripts

- cmd: >-
    pip install virtualenv
    pip install --disable-pip-version-check --upgrade pip
    pip install --upgrade wheel
    pip install install descartes==1.0.1
    pip install numpy>=1.4.1
    pip install pytest
    pip install pytest-cov
    pip install cython==0.29.21
    pip install scipy
    pip install psutil
    pip install imgkit
    pip install chart_studio
    pip install appJar
    pip install importlib-metadata>=3.1.1
    pip install cx_freeze
    pip install shapely
    pip install plotly
    pip install hypothesis
    pip install pandas

cache: '%LOCALAPPDATA%\pip\Cache'

build_script:
- set GEOS_INSTALL=C:\projects\deps\geos-%GEOS_VERSION%-%COMPILER%-%ARCH%
- set CYTHONPF=C:\\projects\\deps\\geos-%GEOS_VERSION%-%COMPILER%-%ARCH%
- set GEOS_C_LIBRARY_PATH=%GEOS_INSTALL%\bin\geos_c.dll
- set GEOS_C_COPY_DIR=C:\lib\site-packages\shapely\DLLs
- set GEOS_C_COPY_PATH=%GEOS_C_COPY_DIR%\geos_c.dll
- set GEOS_FILENAME=geos.dll

- ps: 'Write-Host "Configuring MSVC compiler $env:COMPILER" -ForegroundColor Magenta'
- call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %ARCH%

- ps: 'Write-Host "Configuring PATH with $env:PYTHON and $env:GEOS_INSTALL\bin" -ForegroundColor Magenta'
- set PATH=%PYTHON%;%PYTHON%\Scripts;%GEOS_INSTALL%\bin;%PATH%
- python -m pip install --disable-pip-version-check --upgrade pip
- pip install --upgrade wheel

- ps: 'Write-Host "Checking GEOS build $env:GEOS_INSTALL" -ForegroundColor Magenta'
- if not exist C:\projects\deps mkdir C:\projects\deps
- call %APPVEYOR_BUILD_FOLDER%\build_geos.cmd

- ps: 'Write-Host "Checking geos_c.dll" -ForegroundColor Magenta'
- python -c "import sys; print('Python ' + sys.version)"
- python -c "import ctypes, os; print(ctypes.CDLL(os.environ['GEOS_C_LIBRARY_PATH']))"

- ps: 'Write-Host "Building extension" -ForegroundColor Magenta'
- cd %APPVEYOR_BUILD_FOLDER%
- pip install -r requirements-dev.txt
- python setup.py build_ext --inplace -I%CYTHONPF%\\include -lgeos_c -L%CYTHONPF%\\lib

- ps: 'Write-Host "Running pytest" -ForegroundColor Magenta'
- python -c "import shapely; print(shapely.__version__)"
- python -c "from shapely.geos import geos_version_string; print(geos_version_string)"
- python -c "from shapely import speedups; assert speedups.enabled"
#- python -c "import pandas; pandas.test()"

- ps: 'Write-Host "GEOS built library will be copied from $env:GEOS_C_LIBRARY_PATH to $env:GEOS_C_COPY_PATH" -ForegroundColor Magenta'

- cmd: >-
    echo D|xcopy /S /Q /Y /F "%GEOS_C_LIBRARY_PATH%" "%GEOS_C_COPY_PATH%"

#- ps: 'Write-Host "GEOS built library in $env:GEOS_C_COPY_PATH will be renamed as $env:GEOS_FILENAME" -ForegroundColor Magenta'
#
#- cmd: >-
#    rename "%GEOS_C_COPY_PATH%" "%GEOS_FILENAME"

- ps: 'Write-Host "Run build" -ForegroundColor Magenta'
    
- cmd: >-
    python %APPVEYOR_BUILD_FOLDER%\setup.py build

artifacts:
- path: build\exe.win32-3.6\
  name: carto_acoustique_interieure_win32
# - path: win32install\*.exe
