version: 1.0.{build}
init:
- cmd: SET PATH=c:\python36;c:\python36\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\usr\bin

install:
- cmd: >-
    pip install appJar
    pip install cx_freeze
    pip install shapely
    pip install tkinter
    pip install plotly
    choco install -y nsis.portable -version 3.02.0.20160720
cache: '%LOCALAPPDATA%\pip\Cache'
build_script:
- cmd: >-
    python setup.py build
    python win32install\generate_nsis.py
    makensis win32install\lpstools.nsi
artifacts:
- path: build\exe.win32-3.6\
  name: carto_acoustique_interieure_win32
- path: win32install\*.exe
